### ISSUE TITLE
Realizar el codigo de los componentes electrónicos

### ISSUE THREAD

**Issue by JoaquinCarpio** [JefHuiza/Proyectos_de_Ingenieria#5]
- Desarrollar y configurar el código para cada sensor del proyecto

- [ ] Sensor de pH
- [ ] Sensor de luz
- [ ] Sensor de agua
- [ ] Sensor de dureza
- [ ] Sensor de turbidez

- Generar un código para el control de agua de la minobomba
- Programar la activación y desactivación del suministro de agua al interior del sistema

**Comment by ZULY781** [comment]
- Escribir los códigos para cada sensor que controlen la calidad del agua, la cantidad de la  radiación solar, cantidad de agua recibida
